import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_JP } from 'next/font/google'
import "./globals.css";
import AuthWatcher from '@/app/component/AuthWatcher/AuthWatcher'
import { UserProvider } from '@/app/utils/userContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // 必要な太さだけ指定
  display: 'swap',
  variable: '--font-noto-sans-jp',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="jp">
		<body className={`${geistSans.variable} ${geistMono.variable} ${notoSansJp.variable} antialiased`}>
			<UserProvider>
				<AuthWatcher />
				{children}
			</UserProvider>
		</body>
		</html>
	);
}
