import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_JP } from 'next/font/google';
import { Zen_Maru_Gothic } from 'next/font/google';

import "./globals.css";
import Providers from "@/component/Providers";

import AuthWatcher from '@/component/AuthWatcher'
import { UserProvider } from '@/utils/userContext';
import VhProvider  from '@/component/VhProvider';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // 必要な太さだけ指定
  display: 'swap',
  variable: '--font-noto-sans-jp',
})

const zenMaruGothic = Zen_Maru_Gothic({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // 必要な重みを指定
  display: 'swap',
  variable: '--font-zen-maru-gothic',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
	return (
		<html lang="jp">
			<body className={`content-bg-color ${geistSans.variable} ${geistMono.variable} ${notoSansJp.variable} ${zenMaruGothic.variable} antialiased`}>
				<VhProvider />
                <div id="contents" className="w-[100%]">
					<Providers>
						<AuthWatcher />
						<UserProvider>
							{children}
						</UserProvider>
					</Providers>
				</div>
			</body>
		</html>
	);
}
