import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_JP } from 'next/font/google'
import { Poppins } from "next/font/google";
import "./globals.css";
import AuthWatcher from '@/app/component/AuthWatcher/AuthWatcher'
import { UserProvider } from '@/app/utils/userContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansJp = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // 必要な太さだけ指定
  display: 'swap',
  variable: '--font-noto-sans-jp',
})

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="jp">
		<body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${notoSansJp.variable} antialiased`}>
			<div id="contents" className="w-[100%]">
        <UserProvider>
          <AuthWatcher />
          {children}
        </UserProvider>
      </div>
		</body>
		</html>
	);
}
